### PR TITLE
Converted to VS2013

### PR DESCRIPTION
**Pull request by vanrace**
Hi Mark, 

I had just decided to code this myself and then I stumbled upon your project. It does exactly what I need, but I    overlooked it because it only works with VS2010. I needed it to work in 2012/2013, 

I converted it to VS2013 and made the extension work in VS2012 and VS2013 (no code changes, just configuration). I could not test if it still works in VS2010.

It would be great if you could add these changes and update the extension in the Visual Studio Gallery. This solves a problem a lot of people must have while developing nuget packages for example!

Best regards,

Peter

### CODE REVIEW

**Comment by patrickjamesbarry** [comment]
I was happy to see someone had done this, I was just about to look into myself!  Thanks to both of you for your work. Can this commit be merged?

**Comment by markkemper1** [comment]
Thanks, I've updated the gallery with a new version based on your work to convert it to 2013

**Comment by vanrace** [comment]
Hey thanks, was not counting on it anymore!

I have some changes, but I am not sure to which extend they are custom for our particular situation. If I have time I'll have a look!

Sent from Nine

**Comment by patrickjamesbarry** [comment]
What changes have you made? I am looking for an extension that basically
does this conversion, but also has the capability to revert back to file
assembly references before I make any commits.

Patrick

**Comment by vanrace** [comment]
That is what this one does right? Not automatically of course, may be that is what you mean ?

Sent from Nine

**Comment by patrickjamesbarry** [comment]
From what I have seen, this extension listens in the background and
provides you an option to change any file references to project references,
which is what I want. However, I also need a way to quickly change them
back to "file references" before a commit them to git.

**Comment by vanrace** [comment]
It does at the moment you add a project to which you have file references. If you remove this project from the solution after that it will give you the option to change back to file references again.

Sent from Nine

**Comment by patrickjamesbarry** [comment]
Thank you for pointing this out. I see it now in the docs and tried it out.
It works as documented.  I like the automatic detection, but I would also
like to be able to manually trigger this via the tool menu, by right
clicking on the solution, or some other way....  This would allow me be
revert the projects impacted, to a state they need to be in before I commit
to source control (without me having to unload/remove the project from the
solution).

**Comment by vanrace** [comment]
Sounds like a great feature! I have no clue how to add menus though ;)

Sent from Nine

**Comment by vanrace** [comment]
But should be doable!

Sent from Nine

**Comment by markkemper1** [comment]
I don't have the time to add more features. 

Just a few things to think about.
* If he solution is part of source control, you'll need to remove the projects from the solution file before you commit.
* You'll probably need a way of saving the state of the references so you can switch back correctly (instead of the program trying to guest)
* I'd try to use git to help out  with this, something like
  * Git add and commit the changes 
   * git stash the solution
   * Solution will reload and hopefully prompt to change references back
   * Rebuild and test changes (amend commit if needed)
   * Git stash pop (Solution will be back to initial state)

**Pull request merged**
